# This is a basic workflow to help you get started with Actions

name: Build and release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: '5.0.x'

      # Runs a single command using the runners shell
      - name: Run dotnet
        run: dotnet run -p generator/src/generator.csproj -- . "https://eungu-kwon.github.io/DevOpsKoreaHOL/" _site

      # Runs a single command using the runners shell
      - name: copy asset to _site
        run: ./copy-assets.bash _site

      - name: Set git user
        run: git config --global user.email "kiwi9084@gmail.com" && git config --global user.name "Eungu-Kwon"

      - name: git push to gh_pages
        run: rm .gitignore && git add _site && git commit -m "Auto build gh-pages"

      - name: Push to gh-pages
        run: git subtree push --prefix _site origin gh-pages

      - run: echo "This job's status is ${{ job.status }}."
